# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
all: false
black: true
bootstrap: false
check_commit_message: true
check_manifest: true
check_stray_pulpcore_imports: true
cherry_pick_automation: false
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docker_fixtures: false
docs: false
docs_test: true
plugin_app_label: ansible
plugin_camel: PulpAnsible
plugin_camel_short: Ansible
plugin_caps: PULP_ANSIBLE
plugin_caps_short: ANSIBLE
plugin_dash: pulp-ansible
plugin_dash_short: ansible
plugin_name: pulp_ansible
plugin_snake: pulp_ansible
plugin_snake_short: ansible
publish_docs_to_pulpprojectdotorg: true
pulp_settings:
  ansible_api_hostname: http://pulp:80
  ansible_content_hostname: http://pulp:80/pulp/content
pulpcore_branch: 3.8
pulpcore_pip_version_specifier: "<3.10"
pulpprojectdotorg_key_id: aa499d7938ed
pydocstyle: true
pypi_username: pulp
redmine_project: ansible_plugin
stable_branch: null
test: false
test_bindings: false
test_performance: false
test_released_plugin_with_next_pulpcore_release: false
test_s3: true
travis_addtl_services: []
travis_notifications: []
update_redmine: true

