# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
all: false
black: true
bootstrap: false
check_commit_message: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docs: false
docs_test: true
plugin_app_label: ansible
plugin_camel: PulpAnsible
plugin_camel_short: Ansible
plugin_caps: PULP_ANSIBLE
plugin_caps_short: ANSIBLE
plugin_dash: pulp-ansible
plugin_dash_short: ansible
plugin_name: pulp_ansible
plugin_snake: pulp_ansible
plugin_snake_short: ansible
pydocstyle: true
pypi_username: pulp
test: false
test_bindings: true
test_performance: false
travis_notifications:
  irc:
    channels:
    - chat.freenode.net#pulp-ansible
    on_failure: always
    on_success: change

